name: release build

on:
  release:
    types: [created]

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-20.04,windows-latest]
        target: [x86_64-unknown-linux-gnu,aarch64-pc-windows-msvc]
        bin: [smp-rs,smp-rs.exe]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: cargo build --release

